[build]
  command = "astro build"
  publish = "dist"

# Redirect supaya Decap CMS bisa diakses dari /admin
[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

# Redirect agar semua halaman dinamis tetap berfungsi
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "astro dev"
  port = 8888
  publish = "dist"

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
