backend:
  name: git-gateway
  branch: main
  auth_scope: repo

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

site_url: https://waltahh.netlify.app/

collections:
  - name: "blog"
    label: "Blog Posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Publication Date", name: "pubDate", widget: "datetime" }
      - { label: "Updated Date", name: "updatedDate", widget: "datetime" }
      - { label: "Hero Image", name: "heroImage", widget: "image" }
      - { label: "Content", name: "body", widget: "markdown" }
